### PR TITLE
Adds get_parent method to key class

### PR DESCRIPTION
**Pull request by egalpin**
Simple `key.parent()` method to mirror ndb a bit.  Easily implemented on the fly (it's not much code), so it's a convenience function only.

### CODE REVIEW

**Review by joente — COMMENTED** [review]
I think it's ok, but maybe change the method name to `get_parent()`? We currently are using properties like `kind` and `ks`, and methods like `get_path()` and `get_dict()`.

**Comment by egalpin** [comment]
Sure thing, I was considering this earlier.  Do you feel it better fits as a property (I could add the `@property` decorator) or as a function?

**Comment by joente** [comment]
Its not a big deal but I prefer a method since it returns a new Key() instance.

**Comment by egalpin** [comment]
You got it! Changes inbound

**Review by joente — APPROVED** [review]
Ok

**Pull request merged**
